### PR TITLE
feat: inspecting outline displays properties

### PR DESCRIPTION
**Pull request by amyspark-ng**
now when debug inspecting, the outline component will show width of outline and color of outline

### CODE REVIEW

**Comment by lajbel** [comment]
Can you show an image?

**Comment by amyspark-ng** [comment]
## before:
image

## after: 
image

**Comment by lajbel** [comment]
Awesome, add changelog

**Comment by amyspark-ng** [comment]
is it really necessary, some comps had their properties shown in the inspect window recently such as area showing scale or shader showing shader name but they haven't been added to changelog

**Review by niceEli — APPROVED** [review]
👍🏻

**Comment by amyspark-ng** [comment]
oh nice, thank you eli maybe we should add the changelog for all the other comps too

**Pull request merged**
