### PR TITLE
chore: simplify pr template

### PR DESCRIPTION
**Pull request by lajbel**
## Description

I think the current PR template is kinda annoying, I don't even like to use this, I changed to this, I would like to check if other people likes it

### CODE REVIEW

**Comment by amyspark-ng** [comment]
i personally think is fun but it's not practical

**Comment by lajbel** [comment]
For example, the part of what kind of PR is, is not necessary, that's why we use conventional commit names

**Review by niceEli — APPROVED** [review]
👍🏻

**Comment by amyspark-ng** [comment]
makes me a little sad because eli made it

**Pull request merged**
