### PR TITLE
chore: allow for pkg.pr.new for prs and pushed changes

### PR DESCRIPTION
**Pull request by niceEli**
## Description

this will allow for easy real world testing and pen testing for prs and pushes after the fact, this would also allow for end users to be able to have access the latest version of kaplay.

### Issues or related

- Related Issue # none
- Closes # none

### CODE REVIEW

**Comment by niceEli** [comment]
oops i made a spelling mistake

**Comment by niceEli** [comment]
this commit is for the actual stackblitz pkg.pr.new, i will make another pr eventually for a template (so that you can easy do testing with vite)

**Review by mflerackers — APPROVED** [review]
Looks OK

**Comment by lajbel** [comment]
peak PR

**Pull request merged**
