### PR TITLE
refactor: separate components in files

### PR DESCRIPTION
**Pull request by lajbel**
This is a test PR, to see how it goes, but we have to have a way to have a "global" KaboomCtx, and it should be used in all files so we can separate components and call these functions.

Another approach will be simply separate all functions and only use the state "app"

- [ ] Find a way to separate kaboom methods that depends on another kaboom methods easily

### CODE REVIEW

**Comment by niceEli** [comment]
Is this test or should merge?

**Comment by lajbel** [comment]
Shouldn't

**Comment by amyspark-ng** [comment]
Maybe should move components in categories because having every component in a different file feels bloating

**Comment by mflerackers** [comment]
transform: pos, rotate, scale
draw: sprite, rect, circle, polygon
physics: area, body
animation: timer

**Comment by amyspark-ng** [comment]
yes, yes

**Comment by SpcFORK** [comment]
> Find a way to separate kaboom methods that depends on another kaboom methods easily

Maybe switch to classes?

**Pull request closed without merging**
