### PR TITLE
fix: Ensure required properties exist for `drawUVQuad`

### PR DESCRIPTION
**Pull request by SpcFORK**
## Description

Ensure required properties exist for `drawUVQuad`.

### Issues or related

Type collision.

### CODE REVIEW

**Comment by SpcFORK** [comment]
image
image

---
It is likely that using `null` somewhere in the codebase is a bug, and should be handled with `undefined` instead rather than having two falsey types where one is technically defined.

Maybe somebody wrote a null somewhere, is probably a good idea to refactor if possible.

**Comment by SpcFORK** [comment]
Tests have failed because it seems `drawUVQuad` doesn't need these, so then the push functions should accept undefined.
image

**Review by mflerackers — CHANGES_REQUESTED** [review]
Pos, angle and scale aren't needed, this will break a lot of code. pushTranslate, pushRotate and pushScale are NOP if the params are null.

**Comment by SpcFORK** [comment]
They are gone now, and have been switched for `!`

**Pull request merged**
